// Generated by tools/cascade/export_connections.py. Codex / GPT-6, 2026-10-01.
// Source coordinates remain in metres, Z up.
export const cascadeConnections = {
  "500": {
    "steam_end": [
      0.0,
      1.328,
      2.528
    ],
    "bottom_nozzle": [
      0.0,
      0.078,
      0.105
    ],
    "condensate_nozzle": [
      0,
      0.1080000000000001,
      0.2290000000000001
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 0.07350000000000001,
    "cabinet_shift": [
      0.30199999999999994,
      0.0,
      -0.32199999999999995
    ],
    "feed_end": [
      0.0,
      -0.437,
      1.979
    ],
    "direct_modulation": [
      0.0,
      1.7280000000000002,
      2.129
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "3bc78c8d51be750bd2fbb3c06ca778763076a264338587022ff4e55c860c24d8",
    "modulation_gland": [
      -4.482269266858907e-08,
      1.8100000022649767,
      2.5185000896453857
    ],
    "cabinet_gland": [
      -0.9030000000000001,
      -1.155,
      0.9030000000000001
    ],
    "steam_visual_radius": 0.057
  },
  "1000": {
    "steam_end": [
      0.0,
      1.4380000000000002,
      2.7600000000000002
    ],
    "bottom_nozzle": [
      0.0,
      0.388,
      0.105
    ],
    "condensate_nozzle": [
      0,
      0.388,
      0.23099999999999998
    ],
    "condensate_source_solid": 16,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 0.35350000000000004,
    "cabinet_shift": [
      0.18499999999999994,
      0.0,
      -0.20499999999999996
    ],
    "feed_end": [
      0.0,
      -0.292,
      2.211
    ],
    "direct_modulation": [
      0.0,
      1.838,
      2.3609999999999998
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "8d4cdcf82dd491cebe08b53cc1a9a0d25388e5ea6d79cd55640079af6348e1cb",
    "modulation_gland": [
      -5.91278075390278e-08,
      1.9200000022649766,
      2.750500202178955
    ],
    "cabinet_gland": [
      -1.02,
      -1.155,
      1.02
    ],
    "steam_visual_radius": 0.057
  },
  "1500": {
    "steam_end": [
      0.0,
      1.4580000000000002,
      2.7600000000000002
    ],
    "bottom_nozzle": [
      0.0,
      0.568,
      0.105
    ],
    "condensate_nozzle": [
      0,
      0.568,
      0.23099999999999998
    ],
    "condensate_source_solid": 17,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 0.5335,
    "cabinet_shift": [
      0.18499999999999994,
      0.0,
      -0.20499999999999996
    ],
    "feed_end": [
      0.0,
      0.058,
      2.211
    ],
    "direct_modulation": [
      0.0,
      1.858,
      2.3609999999999998
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "6db8c5fd75d15323c80e1fd4abe4640cdf23cde9f2bd557d61cee5dce1472ea3",
    "modulation_gland": [
      -4.005432119313923e-08,
      1.9400000022649766,
      2.750500202178955
    ],
    "cabinet_gland": [
      -1.02,
      -1.155,
      1.02
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      2.085,
      0.762
    ],
    "eco_out": [
      -0.625,
      2.085,
      1.098
    ],
    "eco_source_sha256": "ea0334f5ce29eb421a3f8a1c006d00270ef8b5d0600d83b3d3e2be1ed4ae3fa3"
  },
  "2000": {
    "steam_end": [
      0.0,
      1.538,
      2.89
    ],
    "bottom_nozzle": [
      0.0,
      0.788,
      0.115
    ],
    "condensate_nozzle": [
      0,
      0.7879999999999999,
      0.241
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 0.7535000000000001,
    "cabinet_shift": [
      0.125,
      0.0,
      -0.135
    ],
    "feed_end": [
      0.0,
      0.218,
      2.241
    ],
    "direct_modulation": [
      0.0,
      1.9380000000000002,
      2.391
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "9cd03dc71ed313573558e536bc32969fcfc5a90b78db1aeedceb7de73e628c01",
    "modulation_gland": [
      3.623962419041504e-08,
      2.0200000022649767,
      2.7805001735687256
    ],
    "cabinet_gland": [
      -1.08,
      -1.155,
      1.09
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      2.305,
      0.736
    ],
    "eco_out": [
      -0.625,
      2.305,
      1.264
    ],
    "eco_source_sha256": "bdf9f9d6dbc013d9da3b75fd9a8bc1e798af4ecf981dc17d8f81ebc4b3140b1d"
  },
  "2500": {
    "steam_end": [
      0.0,
      1.6280000000000001,
      2.89
    ],
    "bottom_nozzle": [
      0.0,
      1.038,
      0.115
    ],
    "condensate_nozzle": [
      0,
      1.038,
      0.241
    ],
    "condensate_source_solid": 16,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 1.0034999999999998,
    "cabinet_shift": [
      0.125,
      0.0,
      -0.135
    ],
    "feed_end": [
      0.0,
      0.418,
      2.241
    ],
    "direct_modulation": [
      0.0,
      2.028,
      2.391
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "69982d95bdc80c9305fb3f9b161d38155e63b125eff32d31a71f10eff6cf5a17",
    "modulation_gland": [
      -1.163482665766935e-07,
      2.1100000022649765,
      2.7805001735687256
    ],
    "cabinet_gland": [
      -1.08,
      -1.155,
      1.09
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      2.555,
      0.736
    ],
    "eco_out": [
      -0.625,
      2.555,
      1.264
    ],
    "eco_source_sha256": "bdf9f9d6dbc013d9da3b75fd9a8bc1e798af4ecf981dc17d8f81ebc4b3140b1d"
  },
  "3000": {
    "steam_end": [
      0.0,
      1.818,
      3.0
    ],
    "bottom_nozzle": [
      0.0,
      1.348,
      0.125
    ],
    "condensate_nozzle": [
      0,
      1.348,
      0.251
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 1.3135,
    "cabinet_shift": [
      0.07499999999999996,
      0.0,
      -0.07499999999999996
    ],
    "feed_end": [
      0.0,
      0.668,
      2.351
    ],
    "direct_modulation": [
      0.0,
      2.218,
      2.501
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "363637cc2cea7acf562f2f6fd89596b87460dfe7b945c94926e8d537d67da886",
    "modulation_gland": [
      6.484985348720329e-08,
      2.3000000022649765,
      2.890500068664551
    ],
    "cabinet_gland": [
      -1.1300000000000001,
      -1.155,
      1.1500000000000001
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      2.865,
      0.7
    ],
    "eco_out": [
      -0.625,
      2.865,
      1.42
    ],
    "eco_source_sha256": "5254de9c832458183277e2a14492477b147d391a8e0808250c60e79b27ec502d"
  },
  "3500": {
    "steam_end": [
      0.0,
      1.8880000000000001,
      3.0
    ],
    "bottom_nozzle": [
      0.0,
      1.548,
      0.125
    ],
    "condensate_nozzle": [
      0,
      1.548,
      0.251
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 1.5134999999999998,
    "cabinet_shift": [
      0.07499999999999996,
      0.0,
      -0.07499999999999996
    ],
    "feed_end": [
      0.0,
      0.808,
      2.351
    ],
    "direct_modulation": [
      0.0,
      2.2880000000000003,
      2.501
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "23127fdf61f37ed860d3477d317e45f5339710df4e521b6f74964cc67852a2c8",
    "modulation_gland": [
      -1.0681152318170462e-07,
      2.3700000022649768,
      2.890500068664551
    ],
    "cabinet_gland": [
      -1.1300000000000001,
      -1.155,
      1.1500000000000001
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      3.065,
      0.7
    ],
    "eco_out": [
      -0.625,
      3.065,
      1.42
    ],
    "eco_source_sha256": "5254de9c832458183277e2a14492477b147d391a8e0808250c60e79b27ec502d"
  },
  "4000": {
    "steam_end": [
      0.0,
      2.1,
      3.0
    ],
    "bottom_nozzle": [
      0.0,
      2.005,
      0.125
    ],
    "condensate_nozzle": [
      0,
      1.975,
      0.251
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.2,
      0.125
    ],
    "rear_face_y": 1.9405,
    "cabinet_shift": [
      -0.0,
      0.0,
      0.0
    ],
    "feed_end": [
      0.0,
      1.26,
      2.501
    ],
    "direct_modulation": [
      0.0,
      2.5,
      2.651
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.1,
      0.125
    ],
    "boiler_source_sha256": "bf5f6fb41e07b4c26c24b00520038cf898e6e1498d9df9143875f41c03aa3ad8",
    "modulation_gland": [
      0.0,
      2.5820000022649765,
      3.0405001640319824
    ],
    "cabinet_gland": [
      -1.205,
      -1.155,
      1.225
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      3.492,
      0.7750003
    ],
    "eco_out": [
      -0.625,
      3.492,
      1.4950008
    ],
    "eco_source_sha256": "0a7e2626dc81be6dc17793b5169ca1434d78d9b195be792f3df71b3e9f91e1bd"
  },
  "5000": {
    "steam_end": [
      0.0,
      2.17,
      3.308
    ],
    "bottom_nozzle": [
      0.0,
      2.355,
      0.133
    ],
    "condensate_nozzle": [
      0,
      2.345,
      0.2589999999999999
    ],
    "condensate_source_solid": 1,
    "bottom_split": [
      0.0,
      2.6,
      0.125
    ],
    "rear_face_y": 2.3104999999999998,
    "cabinet_shift": [
      -0.07499999999999996,
      0.0,
      0.08299999999999996
    ],
    "feed_end": [
      0.0,
      1.48,
      2.659
    ],
    "direct_modulation": [
      0.0,
      2.57,
      2.8089999999999997
    ],
    "tds_end": [
      1.56,
      2.95,
      0.92
    ],
    "bottom_end": [
      2.9,
      3.1,
      0.125
    ],
    "bottom_discharge_start": [
      0.0,
      3.5,
      0.125
    ],
    "boiler_source_sha256": "6595afa20fb05c2c65ec7dd721cb8f677f534e2ba2635652920d335e1e7389ce",
    "modulation_gland": [
      6.675720198856538e-08,
      2.6520000022649763,
      3.198500156402588
    ],
    "cabinet_gland": [
      -1.28,
      -1.155,
      1.308
    ],
    "steam_visual_radius": 0.057,
    "eco_in": [
      -0.625,
      3.862,
      0.762
    ],
    "eco_out": [
      -0.625,
      3.862,
      1.674
    ],
    "eco_source_sha256": "e79e00b6916b63d0998fd31dac6135b9ecd7887b71ef6d4f1e9bb494ff4e5d65"
  }
} as const
