// 2026-10-01 / Codex GPT-6. Derive functional LOD helpers from pinned source.
// Only primitive tessellation changes; centres, radii, node IDs and route data do not.
import {build} from 'esbuild'
import {readFile,writeFile,mkdir} from 'node:fs/promises'
import {resolve,dirname} from 'node:path'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
const here=dirname(fileURLToPath(import.meta.url)),app=resolve(here,'../..'),source=resolve(process.env.LITE_SOURCE||resolve(here,'../../../..'))
execFileSync('git',['-C',source,'diff','--quiet','cc919366206eb317e7f21e90247ed1870cb276cd','--','src/assets','src/components/BoilerConfigurator'])
const evidence=[]
const entry=`
import {Group,Mesh,BoxGeometry,CylinderGeometry,MeshStandardMaterial,Vector3,Quaternion} from 'three';
import {distributionHardware} from './src/components/BoilerConfigurator/distributionGeometry';
import {deaeratorHardware,openDeaeratorPorts} from './src/components/BoilerConfigurator/deaeratorGeometry';
import {selectDeaerator} from './src/components/BoilerConfigurator/deaeratorSelection';
import {greyOrigin,unitSpacing,viewPoint} from './src/components/BoilerConfigurator/cascadeRoutes';
const generated=(geometry,color)=>{const m=new Mesh(geometry,new MeshStandardMaterial({color,roughness:.6,metalness:.25}));m.userData.generatedGeometry=true;return m};
const box=(p,s,c)=>generated(new BoxGeometry(s[0],s[2],s[1]).translate(...viewPoint(p)),c);
function cylinder(id,a,b,r,color){const d=new Vector3(...viewPoint(b)).sub(new Vector3(...viewPoint(a))),mid=new Vector3(...viewPoint(a)).add(new Vector3(...viewPoint(b))).multiplyScalar(.5),geometry=new CylinderGeometry(r,r,d.length(),8);geometry.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0,1,0),d.normalize()));geometry.translate(...mid.toArray());const m=generated(geometry,color);m.name=id;m.userData.semanticId=id;return m;}
/** Apply once after unit clones and shared DA have been added, before prepareMaterials.
 * inputs.trap: source semantic condensate_trap (may be invisible; never modified).
 * inputs.strainer: unchanged 59,816-byte original adl_is16 scene.
 * The caller must load FV module for cascade hardware even when FV is disabled.
 * No route pipes are generated here, so no existing manifest route is removed.
 */
export function applyLiteParts(scene,c,inputs){
 if(scene.getObjectByName('lite_functional_parts'))throw Error('applyLiteParts must run once per scene');
 const borrowed=new Set();for(const input of [inputs.trap,inputs.strainer])input?.traverse(o=>{if(o.isMesh)borrowed.add(o.geometry)});
 const root=new Group();root.name='lite_functional_parts';scene.add(root);
 if(c.cascade>1){
  if(!inputs.trap)throw Error('Lite cascade needs canonical condensate_trap');
  const last=(c.cascade-1)*unitSpacing,[gx,gy]=greyOrigin(c.cascade),support=new Group();support.name='cascade_supports';
  for(const x of [-.55,...Array.from({length:c.cascade-1},(_,i)=>(i+.5)*unitSpacing),last+.7])support.add(box([x,5.6,2.19],[.1,.1,4.38],0x687780),box([x,5.6,.015],[.38,.38,.03],0x687780),box([x,5.6,4.403],[.30,.28,.025],0x687780));
  for(const dx of [-.15,.15])support.add(box([gx+dx,gy+.12,.73],[.038,.038,1.46],0x687780),box([gx+dx,gy+.06,.014],[.1,.43,.028],0x687780));
  for(const z of [1.23,1.48])support.add(box([gx,gy+.137,z],[.4,.028,.035],0x687780));root.add(support);
  const pressure=new Group();pressure.name='cascade_pressure_sensor';pressure.add(box([last+.3,5.6,4.86],[.08,.055,.12],0xd5ddde),box([last+.3,5.571,4.86],[.048,.004,.033],0x252c30));root.add(pressure);
  root.add(distributionHardware(c.cascade,inputs.trap));
 }
 if(c.addons.includes('deaerator')){
  if(!inputs.strainer)throw Error('Lite DA needs canonical ADL IS16 strainer');
  root.add(deaeratorHardware(c.power,c.cascade,inputs.strainer));const da=scene.getObjectByName('deaerator');
  if(!da)throw Error('Lite DA mesh missing');openDeaeratorPorts(da,c.power,c.cascade);
  if(selectDeaerator(c.power,c.cascade)==='da3'){
   const kx=-3.727,ky=-.062,cx=kx-.18*.8660254,cy=ky-.18*.5;
   for(const z of [.760313,1.960313])da.add(cylinder('da3_K_'+z,[kx,ky,z],[cx,cy,z],.0135,0x647680));
   da.add(cylinder('da3_level_column',[cx,cy,.69],[cx,cy,2.03],.027,0x596771),cylinder('da3_level_glass',[cx-.026,cy,.78],[cx-.026,cy,1.94],.009,0xb8aa74));
  }
 }
 root.traverse(o=>{if(o.name==='da_fittings'||o.name.startsWith('cascade_'))o.userData.semanticId=o.name;if(o.isMesh&&!borrowed.has(o.geometry))o.userData.generatedGeometry=true});return root;
}
`
await build({stdin:{contents:entry,resolveDir:source,loader:'ts'},bundle:true,platform:'browser',format:'esm',target:'es2022',external:['three','three/*'],outfile:resolve(app,'src/liteParts.ts'),banner:{js:'// @ts-nocheck\n// Generated by tools/lite/build-parts.mjs from cc919366; Codex / GPT-6; 2026.10.01.1.\n// Low tessellation canonical geometry. Do not hand-edit.'},plugins:[{name:'canonical-visual-tessellation',setup(b){b.onLoad({filter:/\.ts$/},async({path})=>{let contents=await readFile(path,'utf8');const sourceSHA256=createHash('sha256').update(contents).digest('hex');if(/distributionGeometry\.ts$/.test(path)){
 const replacements=[['d.length(),20)','d.length(),8)'],['new TorusGeometry(r,t,6,24)','new TorusGeometry(r,t,4,8)'],['new RingGeometry(bore,r,24)','new RingGeometry(bore,r,8)'],['new CylinderGeometry(r,r,.018,24,1,true)','new CylinderGeometry(r,r,.018,8,1,true)'],['new SphereGeometry(r*1.18,16,10)','new SphereGeometry(r*1.18,8,6)'],['new CylinderGeometry(.061,.061,.001,32)','new CylinderGeometry(.061,.061,.001,8)']];
 for(const[a,z]of replacements){if(!contents.includes(a))throw Error('Source tessellation changed: '+a);contents=contents.replace(a,z)}
 }if(/(?:nativeDeaeratorGeometry|deaeratorGeometry)\.ts$/.test(path))contents=contents.replace(/new SphereGeometry\(([^,]+),20,12\)/g,'new SphereGeometry($1,8,6)');evidence.push({path:path.slice(source.length+1).replaceAll('\\','/'),sourceSHA256,derivedSHA256:createHash('sha256').update(contents).digest('hex')});return {contents,loader:'ts'}})}}]})
await mkdir(resolve(app,'reports'),{recursive:true});await writeFile(resolve(app,'reports/asset-functional-parts-sources.json'),JSON.stringify({sourceCommit:'cc919366206eb317e7f21e90247ed1870cb276cd',method:'Canonical helper bundle; primitive segment counts only reduced. Supports and DA3 columns use source positions verbatim. No duplicate route pipes.',sources:evidence},null,2)+'\n')
console.log('Generated src/liteParts.ts with shared external Three and canonical helper source evidence.')
