// @ts-nocheck
// Generated by tools/lite/build-parts.mjs from cc919366; Codex / GPT-6; 2026.10.01.1.
// Low tessellation canonical geometry. Do not hand-edit.

// <stdin>
import { Group as Group4, Mesh as Mesh2, BoxGeometry as BoxGeometry3, CylinderGeometry as CylinderGeometry2, MeshStandardMaterial as MeshStandardMaterial2, Vector3 as Vector32, Quaternion as Quaternion2 } from "three";

// ../../src/components/BoilerConfigurator/distributionGeometry.ts
import { BoxGeometry, CanvasTexture, CylinderGeometry, Group, Mesh, MeshStandardMaterial, Quaternion, RingGeometry, SphereGeometry, TorusGeometry, Vector3 } from "three";
import { mergeGeometries } from "three/examples/jsm/utils/BufferGeometryUtils.js";

// ../../src/assets/deaerators/catalog.json
var catalog_default = {
  da15_4: {
    label: "\u0414\u0410-15/4",
    source: "PR.15.01.033\u0421\u0411 \u0414\u0435\u0430\u044D\u0440\u0430\u0442\u043E\u0440 \u0414\u0410-15_4.stp",
    matrix: [
      [
        1e-3,
        0,
        0
      ],
      [
        0,
        0,
        -1e-3
      ],
      [
        0,
        1e-3,
        0
      ]
    ],
    offset: [
      -4.2,
      -0,
      1.808
    ],
    center: [
      -4.2,
      0,
      1.808
    ],
    bounds: [
      [
        -5.036,
        -2.275,
        0.96386
      ],
      [
        -3.490111,
        2.275,
        4.783991
      ]
    ],
    ports: {
      feed: {
        point: [
          -4.2,
          1.525,
          1.05
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 100,
        flangeRadius: 0.1075,
        sourceSolid: 30,
        letter: "\u0414",
        sourcePointMM: [
          -0,
          -758,
          -1525
        ]
      },
      drain: {
        point: [
          -4.2,
          -1.525,
          1.05
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 28,
        letter: "\u0413",
        sourcePointMM: [
          0,
          -758,
          1525
        ]
      },
      overflow: {
        point: [
          -5.01,
          -1.525,
          1.808
        ],
        normal: [
          -1,
          0,
          0
        ],
        dn: 80,
        flangeRadius: 0.0975,
        sourceSolid: 51,
        letter: "\u0415",
        sourcePointMM: [
          -810,
          0,
          1525
        ]
      },
      steam: {
        point: [
          -4.2,
          1.525,
          2.616
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 150,
        flangeRadius: 0.14,
        sourceSolid: 24,
        letter: "\u0412",
        sourcePointMM: [
          -0,
          808,
          -1525
        ]
      },
      barb: {
        point: [
          -4.2,
          0.725,
          2.616
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 100,
        flangeRadius: 0.1075,
        sourceSolid: 16,
        letter: "\u0416",
        sourcePointMM: [
          -0,
          808,
          -725
        ]
      },
      flash: {
        point: [
          -4.2,
          -1.325,
          2.616
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 32,
        flangeRadius: 0.0675,
        sourceSolid: 34,
        letter: "\u041B",
        sourcePointMM: [
          -0,
          808,
          1325
        ]
      },
      hotCondensate: {
        point: [
          -4.2,
          0.975,
          2.616
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 26,
        letter: "\u041D",
        sourcePointMM: [
          0,
          808,
          -975
        ]
      },
      recirculation: {
        point: [
          -4.2,
          1.175,
          2.616
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 25,
        flangeRadius: 0.0525,
        sourceSolid: 36,
        letter: "\u041C",
        sourcePointMM: [
          -0,
          808,
          -1175
        ]
      },
      water: {
        point: [
          -4.2,
          -0.595,
          4.704
        ],
        normal: [
          0,
          1,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 117,
        letter: "\u0423 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          0,
          2896,
          595
        ]
      },
      condensate: {
        point: [
          -4.2,
          -1.282,
          4.049
        ],
        normal: [
          0,
          -1,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 106,
        letter: "\u0420 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          0,
          2241,
          1282
        ]
      },
      vent: {
        point: [
          -4.2,
          -0.955,
          4.707
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 102,
        letter: "\u0418 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          0,
          2899,
          955
        ]
      }
    },
    saddleYs: [
      -1.2,
      1.2
    ],
    supportWidth: 1.25,
    supportElevation: 1,
    factoryFloorMM: -808,
    openedCaps: [
      87,
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      164,
      166,
      230
    ],
    flashMode: "factoryNozzle"
  },
  da15_8: {
    label: "\u0414\u0410-15/8",
    source: "PR.15.01.161\u0421\u0411 \u0414\u0435\u0430\u044D\u0440\u0430\u0442\u043E\u0440 \u0414\u0410-15-8.stp",
    matrix: [
      [
        0,
        0,
        1e-3
      ],
      [
        1e-3,
        0,
        0
      ],
      [
        0,
        1e-3,
        0
      ]
    ],
    offset: [
      -4.2,
      -1.92,
      2.1162400000000003
    ],
    center: [
      -4.2,
      0,
      2.11624
    ],
    bounds: [
      [
        -5.336,
        -2.62,
        0.974
      ],
      [
        -3.190023,
        2.62,
        5.392155
      ]
    ],
    ports: {
      feed: {
        point: [
          -4.2,
          1.77,
          1.05524
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 100,
        flangeRadius: 0.1075,
        sourceSolid: 31,
        letter: "\u0414",
        sourcePointMM: [
          3690,
          -1061,
          0
        ]
      },
      drain: {
        point: [
          -4.2,
          -1.72,
          1.05524
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 29,
        letter: "\u0413",
        sourcePointMM: [
          200,
          -1061,
          -0
        ]
      },
      overflow: {
        point: [
          -5.31,
          -1.72,
          2.11624
        ],
        normal: [
          -1,
          0,
          0
        ],
        dn: 80,
        flangeRadius: 0.0975,
        sourceSolid: 23,
        letter: "\u0415",
        sourcePointMM: [
          200,
          -0,
          -1110
        ]
      },
      steam: {
        point: [
          -4.2,
          1.72,
          3.22424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 150,
        flangeRadius: 0.14,
        sourceSolid: 9,
        letter: "\u0412",
        sourcePointMM: [
          3640,
          1108,
          0
        ]
      },
      barb: {
        point: [
          -4.2,
          1.055,
          3.22424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 125,
        flangeRadius: 0.1225,
        sourceSolid: 11,
        letter: "\u0426",
        sourcePointMM: [
          2975,
          1108,
          0
        ]
      },
      flash: {
        point: [
          -3.821042,
          -1.67,
          3.157419
        ],
        normal: [
          0.3420201,
          0,
          0.9396926
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 47,
        letter: "\u0421",
        sourcePointMM: [
          250,
          1041.17943,
          378.95832
        ]
      },
      hotCondensate: {
        point: [
          -4.578958,
          -1.67,
          3.157419
        ],
        normal: [
          -0.3420201,
          0,
          0.9396926
        ],
        dn: 65,
        flangeRadius: 0.09,
        sourceSolid: 49,
        letter: "\u0423",
        sourcePointMM: [
          250,
          1041.17943,
          -378.95832
        ]
      },
      recirculation: {
        point: [
          -3.814201,
          -0.08,
          3.176213
        ],
        normal: [
          0.3420201,
          0,
          0.9396926
        ],
        dn: 32,
        flangeRadius: 0.0675,
        sourceSolid: 51,
        letter: "\u0422",
        sourcePointMM: [
          1840,
          1059.97328,
          385.79872
        ]
      },
      water: {
        point: [
          -4.2,
          -0.56,
          5.31224
        ],
        normal: [
          0,
          1,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 401,
        letter: "\u0423 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          1360,
          3196,
          -0
        ]
      },
      condensate: {
        point: [
          -4.2,
          -1.247,
          4.65724
        ],
        normal: [
          0,
          -1,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 392,
        letter: "\u0420 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          673,
          2541,
          0
        ]
      },
      vent: {
        point: [
          -4.2,
          -0.92,
          5.31524
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 388,
        letter: "\u0418 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          1e3,
          3199,
          -0
        ]
      }
    },
    saddleYs: [
      -1.32,
      1.32
    ],
    supportWidth: 1.62,
    supportElevation: 1,
    factoryFloorMM: -1116.24,
    openedCaps: [
      117,
      143,
      169,
      183,
      291,
      316,
      331,
      356,
      407,
      421,
      458
    ],
    flashMode: "factoryNozzle"
  },
  da25_15: {
    label: "\u0414\u0410-25/15",
    source: "PR.25.01.269\u0421\u0411 \u0414\u0435\u0430\u044D\u0440\u0430\u0442\u043E\u0440 \u0414\u0410-25_15.stp",
    matrix: [
      [
        0,
        0,
        1e-3
      ],
      [
        1e-3,
        0,
        0
      ],
      [
        0,
        1e-3,
        0
      ]
    ],
    offset: [
      -4.2,
      4.50904240827667,
      0.624029
    ],
    center: [
      -4.2,
      0,
      2.223557
    ],
    bounds: [
      [
        -5.436,
        -3.225,
        1
      ],
      [
        -3.09019,
        3.225,
        5.405057
      ]
    ],
    ports: {
      feed: {
        point: [
          -4.2,
          2.28,
          1.055557
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 150,
        flangeRadius: 0.14,
        sourceSolid: 16,
        letter: "\u0414",
        sourcePointMM: [
          -2229.04241,
          431.52798,
          0
        ]
      },
      drain: {
        point: [
          -4.2,
          -2.33,
          1.055557
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 14,
        letter: "\u0413",
        sourcePointMM: [
          -6839.04241,
          431.52798,
          0
        ]
      },
      overflow: {
        point: [
          -5.408,
          -2.33,
          2.223557
        ],
        normal: [
          -1,
          0,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 36,
        letter: "\u0415",
        sourcePointMM: [
          -6839.04241,
          1599.52798,
          -1208
        ]
      },
      steam: {
        point: [
          -4.2,
          2.28,
          3.431557
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 200,
        flangeRadius: 0.1675,
        sourceSolid: 8,
        letter: "\u0412",
        sourcePointMM: [
          -2229.04241,
          2807.52798,
          0
        ]
      },
      barb: {
        point: [
          -4.2,
          1.46,
          3.431557
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 150,
        flangeRadius: 0.14,
        sourceSolid: 6,
        letter: "\u041F",
        sourcePointMM: [
          -3049.04241,
          2807.52798,
          0
        ]
      },
      flash: {
        point: [
          -4.2,
          0.07,
          3.431557
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 80,
        flangeRadius: 0.0975,
        sourceSolid: 20,
        letter: "\u041A",
        sourcePointMM: [
          -4439.04241,
          2807.52798,
          0
        ]
      },
      hotCondensate: {
        point: [
          -3.689477,
          2.28,
          3.318377
        ],
        normal: [
          0.4226183,
          0,
          0.9063078
        ],
        dn: 65,
        flangeRadius: 0.09,
        sourceSolid: 22,
        letter: "\u041C",
        sourcePointMM: [
          -2229.04241,
          2694.34779,
          510.52286
        ]
      },
      recirculation: {
        point: [
          -4.2,
          -0.33,
          3.431557
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 80,
        flangeRadius: 0.0975,
        sourceSolid: 10,
        letter: "\u041B",
        sourcePointMM: [
          -4839.04241,
          2807.52798,
          0
        ]
      },
      water: {
        point: [
          -3.896,
          -1.806543,
          4.846557
        ],
        normal: [
          0.5,
          -0.8660254,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 359,
        letter: "\u0412 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          -6315.58586,
          4222.52798,
          304
        ]
      },
      condensate: {
        point: [
          -4.094422,
          -1.878763,
          4.846557
        ],
        normal: [
          0.1736482,
          -0.9848078,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 357,
        letter: "\u0411 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          -6387.80553,
          4222.52798,
          105.57809
        ]
      },
      vent: {
        point: [
          -4.2,
          -1.57,
          5.331557
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 348,
        letter: "\u0414 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          -6079.04241,
          4707.52798,
          0
        ]
      }
    },
    saddleYs: [
      -1.73,
      1.73
    ],
    supportWidth: 1.79,
    supportElevation: 1,
    factoryFloorMM: 375.971,
    openedCaps: [
      95,
      97,
      101,
      103,
      105,
      107,
      267,
      281,
      395,
      481,
      495
    ],
    flashMode: "factoryNozzle"
  },
  da25_25: {
    label: "\u0414\u0410-25/25",
    source: "PR.25.01.268\u0421\u0411 \u0414\u0435\u0430\u044D\u0440\u0430\u0442\u043E\u0440 \u0414\u0410-25-25-1.stp",
    matrix: [
      [
        0,
        0,
        1e-3
      ],
      [
        1e-3,
        0,
        0
      ],
      [
        0,
        1e-3,
        0
      ]
    ],
    offset: [
      -4.2,
      -3.33,
      2.429424
    ],
    center: [
      -4.2,
      0,
      2.429424
    ],
    bounds: [
      [
        -5.6435,
        -4.23,
        0.986
      ],
      [
        -2.840116,
        4.23,
        6.075328
      ]
    ],
    ports: {
      feed: {
        point: [
          -4.2,
          3.13,
          1.046424
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 200,
        flangeRadius: 0.1675,
        sourceSolid: 15,
        letter: "\u0414",
        sourcePointMM: [
          6460,
          -1383,
          0
        ]
      },
      drain: {
        point: [
          -4.2,
          -3.13,
          1.046424
        ],
        normal: [
          0,
          0,
          -1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 13,
        letter: "\u0413",
        sourcePointMM: [
          200,
          -1383,
          0
        ]
      },
      overflow: {
        point: [
          -5.616,
          -3.13,
          2.429424
        ],
        normal: [
          -1,
          0,
          0
        ],
        dn: 150,
        flangeRadius: 0.14,
        sourceSolid: 16,
        letter: "\u0415",
        sourcePointMM: [
          200,
          0,
          -1416
        ]
      },
      steam: {
        point: [
          -4.2,
          3.13,
          3.837424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 250,
        flangeRadius: 0.2025,
        sourceSolid: 2,
        letter: "\u0412",
        sourcePointMM: [
          6460,
          1408,
          0
        ]
      },
      barb: {
        point: [
          -4.2,
          2.08,
          3.837424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 200,
        flangeRadius: 0.1675,
        sourceSolid: 61,
        letter: "\u041C",
        sourcePointMM: [
          5410,
          1408,
          0
        ]
      },
      hotCondensate: {
        point: [
          -4.2,
          2.58,
          3.837424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 80,
        flangeRadius: 0.0975,
        sourceSolid: 76,
        letter: "\u041A",
        sourcePointMM: [
          5910,
          1408,
          -0
        ]
      },
      recirculation: {
        point: [
          -4.2,
          -2.6,
          3.837424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 4,
        letter: "\u0418",
        sourcePointMM: [
          730,
          1408,
          0
        ]
      },
      water: {
        point: [
          -4.2,
          -0.925,
          5.985424
        ],
        normal: [
          0,
          1,
          0
        ],
        dn: 65,
        flangeRadius: 0.09,
        sourceSolid: 207,
        letter: "\u0415 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          2405,
          3556,
          -0
        ]
      },
      condensate: {
        point: [
          -4.2,
          -1.738,
          5.260424
        ],
        normal: [
          0,
          -1,
          0
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 91,
        letter: "\u0414 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          1592,
          2831,
          0
        ]
      },
      vent: {
        point: [
          -4.2,
          -1.42,
          5.745424
        ],
        normal: [
          0,
          0,
          1
        ],
        dn: 50,
        flangeRadius: 0.08,
        sourceSolid: 86,
        letter: "\u0418 \u043A\u043E\u043B\u043E\u043D\u043A\u0438",
        sourcePointMM: [
          1910,
          3316,
          0
        ]
      }
    },
    saddleYs: [
      -2.28,
      2.28
    ],
    supportWidth: 2.14,
    supportElevation: 1,
    factoryFloorMM: -1429.424,
    openedCaps: [
      136,
      138,
      237,
      254,
      256,
      275,
      276,
      277,
      279,
      561
    ],
    flashMode: "steamTee"
  }
};

// ../../src/components/BoilerConfigurator/familyRules.ts
function boilerCount(value) {
  const count = Number(value);
  return Number.isInteger(count) && count >= 2 && count <= 5 ? count : 1;
}

// ../../src/components/BoilerConfigurator/deaeratorSelection.ts
function selectDeaerator(power, count = 1) {
  const units = boilerCount(count), total = power * units;
  if (units === 1) {
    if (power < 1500) return "da3";
    if (power <= 2500) return "da15_4";
    if (power <= 3500) return "da15_8";
    return power <= 1e4 ? "da25_15" : "da25_25";
  }
  if (total <= 2500) return "da3";
  if (total <= 5e3) return "da15_4";
  if (total <= 6e3) return "da15_8";
  return total <= 1e4 ? "da25_15" : "da25_25";
}

// ../../src/components/BoilerConfigurator/deaeratorPorts.ts
var da3PressurePort = [-3.61194531, 0.81194531, 1.760313];
function da3InstrumentPoint(out, along = 0, dz = 0) {
  const n = Math.SQRT1_2, p = da3PressurePort;
  return [p[0] - out * n + along * n, p[1] + out * n + along * n, p[2] + dz];
}
function nativeDeaerator(power, count = 1) {
  const kind = selectDeaerator(power, count);
  return kind === "da3" ? void 0 : catalog_default[kind];
}
function deaeratorPorts(power, count = 1) {
  const native = nativeDeaerator(power, count);
  if (!native) return {
    feed: [-3.1, -0.392321, 0.4],
    feedDN: 50,
    overflow: [-3.1, -0.429, 1.760313],
    drain: [-3.31, 0.3, 0.153313],
    water: [-3.503, 0.115, 2.510313],
    condensate: [-3.1, 0.55, 2.579813],
    hotCondensate: [-3.1, 0.55, 2.579813],
    recirculation: [-4.7, 0.55, 3.2],
    // shared condensate inlet tee on DA3
    vent: [-3.1, 0, 2.547813],
    steam: [-3.832, 0.3, 0.880313],
    flash: [-3.832, 0.3, 0.880313],
    barb: [-3.1, -0.325, 2.435313],
    openedCaps: [63, 64, 67, 68, 72]
  };
  const p = native.ports;
  return {
    feed: p.feed.point,
    feedDN: p.feed.dn,
    overflow: p.overflow.point,
    drain: p.drain.point,
    water: p.water.point,
    condensate: p.condensate.point,
    hotCondensate: p.hotCondensate.point,
    recirculation: p.recirculation.point,
    vent: p.vent.point,
    steam: p.steam.point,
    barb: p.barb.point,
    // 25/25 has no dedicated flash-steam nozzle: return joins the heating-steam branch.
    flash: p.flash?.point || [p.steam.point[0], p.steam.point[1], p.steam.point[2] + 0.8],
    openedCaps: native.openedCaps
  };
}

// ../../src/components/BoilerConfigurator/nativeDeaeratorRoutes.ts
var approach = (p, d = 0.4) => p.point.map((v, i) => v + p.normal[i] * d);
var pipeRadius = (dn) => ({ 20: 0.0135, 25: 0.01685, 32: 0.0212, 50: 0.0285, 65: 0.038, 80: 0.0445, 100: 0.054, 125: 0.0665, 150: 0.0795, 200: 0.1095, 250: 0.1365 })[dn] || dn / 2e3 + 4e-3;
function deaeratorLayout(n) {
  return {
    front: n.bounds[0][1] - 0.75,
    rear: n.bounds[1][1] + 0.65,
    steamZ: n.ports.steam.point[2] + 0.8,
    hotZ: n.ports.steam.point[2] + 1.3,
    recircZ: n.ports.steam.point[2] + 1.6,
    flashZ: n.ports.steam.point[2] + 1.1
  };
}

// ../../src/components/BoilerConfigurator/steamDistribution.ts
var distributionOutletCount = 3;
function distributionLayout(count) {
  const last = (count - 1) * 6.3, x = last + 4.4, z = 1.85, y0 = 2.05, y1 = 5.05;
  const outlets = Array.from({ length: distributionOutletCount }, (_, i) => y0 + 0.5 + i * 0.85);
  return {
    last,
    x,
    z,
    y0,
    y1,
    outlets,
    radius: 0.213,
    drainY: y1 - 0.3,
    drainZ: 0.72,
    takeoffs: [y0 + 0.24, y1 - 0.3],
    drainX: x + 0.4,
    trap: [x + 1.1, y1 - 0.3, 0.72]
  };
}

// ../../src/components/BoilerConfigurator/cascadeRoutes.ts
var unitSpacing = 6.3;
var greyOrigin = (count) => [(Math.floor((count - 1) / 2) + 0.5) * unitSpacing, -3.05, 1.15];
var viewPoint = ([x, y, z]) => [x, z, -y];

// ../../src/components/BoilerConfigurator/distributionGeometry.ts
var colors = { steel: "#76828a", blue: "#235b9a", dark: "#303940", silver: "#a4acb3", white: "#ececec" };
function item(g, color = "steel") {
  const m = new Mesh(g, new MeshStandardMaterial({ color: colors[color] || color, metalness: 0.4, roughness: 0.46 }));
  m.userData.generatedGeometry = true;
  return m;
}
function cylinder(a, b, r, color = "steel", r2 = r) {
  const start = new Vector3(...viewPoint(a)), end = new Vector3(...viewPoint(b)), d = end.clone().sub(start);
  const g = new CylinderGeometry(r2, r, d.length(), 8);
  g.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0, 1, 0), d.normalize()));
  const p = start.add(end).multiplyScalar(0.5);
  g.translate(p.x, p.y, p.z);
  return item(g, color);
}
function torus(center, normal, r, t, color = "dark") {
  const g = new TorusGeometry(r, t, 4, 8), n = new Vector3(...viewPoint(normal)).normalize();
  g.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), n));
  g.translate(...viewPoint(center));
  return item(g, color);
}
function flange(root, p, normal, r, bore) {
  const axis = new Vector3(...viewPoint(normal)).normalize(), center = new Vector3(...viewPoint(p));
  const q = new Quaternion().setFromUnitVectors(new Vector3(0, 0, 1), axis);
  for (const side of [-1, 1]) {
    const g = new RingGeometry(bore, r, 8);
    g.applyQuaternion(q);
    const c = center.clone().addScaledVector(axis, side * 9e-3);
    g.translate(c.x, c.y, c.z);
    const m = item(g);
    m.material.side = 2;
    root.add(m);
  }
  const shell = new CylinderGeometry(r, r, 0.018, 8, 1, true);
  shell.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0, 1, 0), axis));
  shell.translate(center.x, center.y, center.z);
  root.add(item(shell));
  for (let i = 0; i < 8; i++) {
    const a = i * Math.PI / 4, c = new Vector3(Math.cos(a) * r * 0.8, Math.sin(a) * r * 0.8, 0).applyQuaternion(q).add(center);
    const g = new CylinderGeometry(7e-3, 7e-3, 0.03, 6);
    g.applyQuaternion(new Quaternion().setFromUnitVectors(new Vector3(0, 1, 0), axis));
    g.translate(c.x, c.y, c.z);
    root.add(item(g, "silver"));
  }
}
function valve(root, p, vertical, s = 1) {
  const [x, y, z] = p, half = 0.12 * s, r = 0.073 * s;
  const a = vertical ? [x, y, z - half] : [x - half, y, z], b = vertical ? [x, y, z + half] : [x + half, y, z];
  root.add(cylinder(a, b, r, "blue"));
  const ball = new SphereGeometry(r * 1.18, 8, 6);
  ball.scale(1, 0.8, 1);
  ball.translate(...viewPoint(p));
  root.add(item(ball, "blue"));
  flange(root, a, vertical ? [0, 0, 1] : [1, 0, 0], 0.102 * s, 0.048 * s);
  flange(root, b, vertical ? [0, 0, 1] : [1, 0, 0], 0.102 * s, 0.048 * s);
  const stem = vertical ? [x - 0.25 * s, y, z] : [x, y, z + 0.25 * s];
  root.add(cylinder(p, stem, 0.014 * s, "silver"), torus(stem, vertical ? [1, 0, 0] : [0, 0, 1], 0.093 * s, 0.01 * s));
  for (const sign of [-1, 1]) root.add(cylinder(stem, vertical ? [stem[0], y + sign * 0.09 * s, z] : [x + sign * 0.09 * s, y, stem[2]], 8e-3 * s, "dark"));
}
function pressureGauge(root, p) {
  const [x, y, z] = p;
  root.add(cylinder([x, y, z - 0.16], p, 7e-3, "silver"));
  root.add(cylinder([x - 0.016, y, z + 0.065], [x + 0.016, y, z + 0.065], 0.068, "silver"));
  const canvas = document.createElement("canvas");
  canvas.width = 256;
  canvas.height = 256;
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = "#f4f4ef";
  ctx.fillRect(0, 0, 256, 256);
  ctx.strokeStyle = "#30363a";
  ctx.lineWidth = 3;
  for (let i = 0; i <= 16; i++) {
    const a = (0.75 + i / 16 * 1.5) * Math.PI;
    ctx.beginPath();
    ctx.moveTo(128 + 95 * Math.cos(a), 128 + 95 * Math.sin(a));
    ctx.lineTo(128 + 82 * Math.cos(a), 128 + 82 * Math.sin(a));
    ctx.stroke();
  }
  ctx.font = "20px Arial";
  ctx.fillStyle = "#30363a";
  ctx.fillText("\u0431\u0430\u0440", 110, 180);
  ctx.lineWidth = 4;
  ctx.beginPath();
  ctx.moveTo(128, 128);
  ctx.lineTo(71, 181);
  ctx.stroke();
  const t = new CanvasTexture(canvas), g = new CylinderGeometry(0.061, 0.061, 1e-3, 8);
  g.rotateZ(Math.PI / 2);
  g.translate(...viewPoint([x + 0.017, y, z + 0.065]));
  const dial = item(g, "white");
  dial.material.map = t;
  dial.userData.generatedTexture = true;
  root.add(dial);
}
function mergeStaticFittings(root) {
  const batches = /* @__PURE__ */ new Map();
  for (const child of root.children) if (child instanceof Mesh && !child.userData.generatedTexture) {
    const material = child.material, key = material.color.getHexString() + ":" + material.side;
    const batch = batches.get(key) || [];
    batch.push(child);
    batches.set(key, batch);
  }
  for (const batch of batches.values()) {
    const merged = new Mesh(mergeGeometries(batch.map((m) => m.geometry)), batch[0].material.clone());
    merged.userData.generatedGeometry = true;
    batch.forEach((m) => {
      m.removeFromParent();
      m.geometry.dispose();
      m.material.dispose();
    });
    root.add(merged);
  }
}
function axisValve(root, p, axis, scale = 0.6, actuator = false) {
  const assembly = new Group();
  valve(assembly, [0, 0, 0], false, scale);
  if (actuator) assembly.add(item(new BoxGeometry(0.13, 0.14, 0.1).translate(0, 0.23 * scale + 0.07, 0), "dark"));
  const q = new Quaternion().setFromUnitVectors(new Vector3(1, 0, 0), new Vector3(...viewPoint(axis)).normalize());
  for (const child of [...assembly.children]) if (child instanceof Mesh) {
    child.geometry.applyQuaternion(q);
    child.geometry.translate(...viewPoint(p));
    root.add(child);
  }
}
function strainer(root, p, s = 0.6, steam = false) {
  const [x, y, z] = p;
  const point = (dx, drop) => steam ? [x + dx * s, y - drop * s, z] : [x + dx * s, y, z - drop * s];
  root.add(cylinder([x - 0.1 * s, y, z], [x + 0.1 * s, y, z], 0.052 * s, "blue"), cylinder(p, point(0.14, 0.17), 0.042 * s, "blue"), cylinder(point(0.12, 0.15), point(0.17, 0.2), 0.05 * s, "silver"));
}
function steamStrainer(root, p, source) {
  const model = source.clone(true);
  model.name = "adl_steam_strainer";
  model.position.set(...viewPoint(p));
  model.visible = true;
  model.userData.strainer = { manufacturer: "\u0410\u0414\u041B", model: "IS16 DN100", pipeAxis: [1, 0, 0], coverDirection: [0, -1, 0], center: p };
  root.add(model);
}
function distributionHardware(count, sourceTrap) {
  const root = new Group();
  root.name = "cascade_distribution_fittings";
  const { x, z, y0, y1, outlets, radius, drainY: y, drainZ: h, trap, takeoffs } = distributionLayout(count);
  root.add(cylinder([x, y0 - 0.012, z], [x, y0 + 0.012, z], radius));
  flange(root, [x, y1, z], [0, 1, 0], 0.255, 0.1095);
  valve(root, [x, 5.6, 2.9], true, 2);
  outlets.forEach((yy) => {
    valve(root, [x, yy, 2.37], true);
    flange(root, [x + 1.5, yy, 2.8], [1, 0, 0], 0.102, 0.048);
  });
  pressureGauge(root, [x, y1 - 0.32, z + 0.31]);
  for (const yy of [y0 + 0.65, y1 - 0.8]) {
    for (const xx of [x - 0.28, x + 0.28]) {
      root.add(item(new BoxGeometry(0.06, z - radius - 0.03, 0.06).translate(...viewPoint([xx, yy, (z - radius - 0.03) / 2])), "dark"));
      root.add(item(new BoxGeometry(0.22, 0.025, 0.22).translate(...viewPoint([xx, yy, 0.0125])), "silver"));
    }
    root.add(item(new BoxGeometry(0.66, 0.08, 0.09).translate(...viewPoint([x, yy, z - radius - 0.05])), "dark"));
    root.add(torus([x, yy, z], [0, 1, 0], radius + 8e-3, 8e-3, "silver"));
  }
  for (const yy of takeoffs) root.add(cylinder([x, yy, 1.05], [x, yy, 0.91], 0.0445, "steel", 0.02415));
  root.add(cylinder([x + 0.59, y, h], [x + 0.69, y, h], 0.02415, "steel", 0.01685));
  const trapRoot = new Group();
  trapRoot.name = "cascade_distribution_trap";
  trapRoot.position.set(...viewPoint(trap));
  trapRoot.rotation.y = Math.PI;
  const actual = sourceTrap.clone(true);
  actual.name = "distribution_trap_model";
  actual.position.sub(new Vector3(3.02, 0.48, -4.35));
  actual.visible = true;
  trapRoot.add(actual);
  root.add(trapRoot);
  for (const xx of [x + 0.78, x + 1.65]) valve(root, [xx, y, h], false, 0.34);
  valve(root, [x + 1.1, y - 0.4, h], false, 0.34);
  strainer(root, [x + 0.92, y, h], 0.52);
  root.add(cylinder([x + 1.4, y, h], [x + 1.455, y, h], 0.034, "blue"));
  flange(root, [x + 1.38, y, h], [1, 0, 0], 0.055, 0.014);
  flange(root, [x + 1.475, y, h], [1, 0, 0], 0.055, 0.014);
  flange(root, [x + 1.92, 6.9, h], [0, 1, 0], 0.055, 0.014);
  mergeStaticFittings(root);
  return root;
}

// ../../src/components/BoilerConfigurator/deaeratorGeometry.ts
import { BoxGeometry as BoxGeometry2, Group as Group3, SphereGeometry as SphereGeometry3 } from "three";

// ../../src/components/BoilerConfigurator/nativeDeaeratorGeometry.ts
import { Group as Group2, SphereGeometry as SphereGeometry2 } from "three";
function nativeDeaeratorHardware(n, count, sourceStrainer) {
  const root = new Group2();
  root.name = "da_fittings";
  const p = n.ports, l = deaeratorLayout(n);
  const inlet = (y2, z, regulated) => {
    for (const x of [-7.98, -6.66]) axisValve(root, [x, y2, z], [1, 0, 0], 0.6);
    if (regulated) {
      strainer(root, [-7.71, y2, z], 0.7);
      axisValve(root, [-7.2, y2, z], [1, 0, 0], 0.65, true);
    }
    root.add(cylinder([-6.98, y2, z], [-6.9, y2, z], 0.054, "blue"));
  };
  inlet(l.front, 1.6, true);
  inlet(l.front - 0.5, 3.8, false);
  const hot = approach(p.hotCondensate);
  for (const z of [3.6, 4.1]) axisValve(root, [-6.15, -3, z], [0, 0, 1], 0.62);
  root.add(cylinder([-6.15, -3, 3.84], [-6.15, -3, 3.94], 0.065, "blue"));
  root.userData.hotCondensateApproach = hot;
  for (let i = 0; i < count; i++) {
    const x = i * unitSpacing + 2.72;
    axisValve(root, [x, 1.3, 1.8], [0, 1, 0], 0.28);
    root.add(cylinder([x, 1.55, 1.8], [x, 1.6, 1.8], 0.029, "blue"));
  }
  steamStrainer(root, [-6.95, l.rear, l.steamZ], sourceStrainer);
  const mainScale = pipeRadius(p.steam.dn) / 0.048;
  axisValve(root, [-5.86, l.rear, l.steamZ], [1, 0, 0], mainScale, true);
  axisValve(root, [-4.78, l.rear, l.steamZ], [1, 0, 0], mainScale);
  const barbScale = pipeRadius(p.barb.dn) / 0.048;
  for (const [x, actuator] of [[-5.88, true], [-4.85, false]])
    axisValve(root, [x, p.barb.point[1], l.steamZ], [1, 0, 0], barbScale, actuator);
  axisValve(root, [-3.45, 2.35, 0.45], [1, 0, 0], pipeRadius(p.feed.dn) / 0.048);
  const a = [-2.5, 2.35, 0.45], b = [-2.2, 2.35, 0.45];
  root.add(cylinder(a, b, pipeRadius(p.feed.dn), "#328553", count > 1 ? 0.054 : 0.028));
  root.userData.feedReducer = { a, b, inletDN: p.feed.dn, outletDiameter: count > 1 ? 0.108 : 0.056 };
  const y = p.overflow.point[1], r = Math.max(0.13, pipeRadius(p.overflow.dn) * 1.8);
  const ball = new SphereGeometry2(r, 8, 6);
  ball.translate(...viewPoint([-7.62, y, 0.4]));
  root.add(item(ball, "blue"));
  for (const x of [-7.62 - r - 0.06, -7.62 + r + 0.06]) flange(root, [x, y, 0.4], [1, 0, 0], r * 0.92, pipeRadius(p.overflow.dn) * 0.92);
  axisValve(root, [-6.6, l.front, 0.62], [1, 0, 0], 0.65);
  for (const [name, port] of Object.entries(p)) {
    const center = approach(port, 0.012);
    flange(root, center, port.normal, port.flangeRadius, pipeRadius(port.dn) * 0.93);
    if (name === "flash" && port.dn !== 50) {
      const reducer = cylinder(approach(port, 0.22), port.point, 0.0285, "steel", pipeRadius(port.dn));
      reducer.name = "da_flash_reducer";
      root.add(reducer);
    }
  }
  mergeStaticFittings(root);
  return root;
}

// ../../src/components/BoilerConfigurator/deaeratorGeometry.ts
function deaeratorHardware(power, count, sourceStrainer) {
  const native = nativeDeaerator(power, count);
  if (native) return nativeDeaeratorHardware(native, count, sourceStrainer);
  const root = new Group3();
  root.name = "da_fittings";
  const small = true, p = deaeratorPorts(power, count);
  for (const x of [-6.25, -5.05]) axisValve(root, [x, -2.6, 1.6], [1, 0, 0], 0.48);
  strainer(root, [-6.02, -2.6, 1.6], 0.65);
  axisValve(root, [-5.65, -2.6, 1.6], [1, 0, 0], 0.55, true);
  root.add(cylinder([-5.31, -2.6, 1.6], [-5.25, -2.6, 1.6], 0.05, "blue"));
  for (const x of [-6.22, -4.95]) axisValve(root, [x, -3, 3.2], [1, 0, 0], 0.5);
  root.add(cylinder([-5.92, -3, 3.2], [-5.85, -3, 3.2], 0.05, "blue"));
  if (!small) {
    for (const x of [-6.22, -5.15]) axisValve(root, [x, -3.4, 3.8], [1, 0, 0], 0.5);
    root.add(cylinder([-5.92, -3.4, 3.8], [-5.85, -3.4, 3.8], 0.05, "blue"));
  }
  for (let i = 0; i < count; i++) {
    const x = i * unitSpacing + 2.72;
    axisValve(root, [x, 1.3, 1.8], [0, 1, 0], 0.28);
    root.add(cylinder([x, 1.55, 1.8], [x, 1.6, 1.8], 0.029, "blue"));
  }
  steamStrainer(root, [-5.55, 2.8, 3.2], sourceStrainer);
  axisValve(root, [-4.85, 2.8, 3.2], [1, 0, 0], 0.9, true);
  axisValve(root, [-4.4, 2.8, 3.2], [1, 0, 0], 0.95);
  axisValve(root, [-5.2, 1.75, 3.2], [0, -1, 0], 0.65, true);
  axisValve(root, [-5.2, 1.2, 3.2], [0, -1, 0], 0.65);
  if (small) axisValve(root, [-2.36, 2.35, 0.4], [1, 0, 0], 0.52);
  else axisValve(root, [-3.65, 1.525, 0.91], [0, 0, -1], 0.7);
  const y = small ? -0.8 : -1.525;
  const body = new SphereGeometry3(0.12, 8, 6);
  body.translate(...viewPoint([-5.22, y, 0.29]));
  root.add(item(body, "blue"));
  flange(root, [-5.38, y, 0.35], [1, 0, 0], 0.09, 0.024);
  flange(root, [-5.06, y, 0.35], [1, 0, 0], 0.09, 0.024);
  axisValve(root, [-4.6, small ? -2.2 : -2.8, small ? 0.153313 : 0.62], [1, 0, 0], small ? 0.24 : 0.5);
  axisValve(root, [p.vent[0], p.vent[1], 2.97], [0, 0, 1], 0.22);
  flange(root, da3PressurePort, [-Math.SQRT1_2, Math.SQRT1_2, 0], 0.0525, 0.012);
  pressureGauge(root, da3InstrumentPoint(0.36, -0.2, 0.28));
  axisValve(root, da3InstrumentPoint(0.36, -0.2, 0.2), [0, 0, 1], 0.16);
  for (const along of [-0.04, 0.13, 0.29]) root.add(cylinder(da3InstrumentPoint(0.36, along, 0.12), da3InstrumentPoint(0.36, along, 0.22), 9e-3, "silver"));
  root.add(cylinder(da3InstrumentPoint(0.36, -0.04, 0.18), da3InstrumentPoint(0.36, -0.04, 0.26), 0.021, "silver"));
  const transmitter = new BoxGeometry2(0.067, 0.07, 0.048);
  transmitter.translate(...viewPoint(da3InstrumentPoint(0.36, 0.13, 0.285)));
  root.add(item(transmitter, "dark"));
  axisValve(root, da3InstrumentPoint(0.36, 0.13, 0.2), [0, 0, 1], 0.14);
  root.add(cylinder(da3InstrumentPoint(0.36, 0.29, 0.215), da3InstrumentPoint(0.36, 0.29, 0.229), 0.035, "silver"));
  root.userData.pressureGroup = { source: "\u0413\u0440\u0443\u043F\u043F\u0430 \u0431\u0435\u0437\u043E\u043F\u0430\u0441\u043D\u043E\u0441\u0442\u0438 \u0414\u0410-3, \u0410\u041A\u041C\u0410\u0419", nozzle: "\u041E", dn: 20, point: da3PressurePort };
  flange(root, p.feed, small ? [0, -1, 0] : [0, 0, -1], small ? 0.08 : 0.1075, small ? 0.025 : 0.05);
  flange(root, p.overflow, small ? [0, -1, 0] : [-1, 0, 0], small ? 0.08 : 0.0975, small ? 0.025 : 0.04);
  mergeStaticFittings(root);
  return root;
}
function openDeaeratorPorts(da, power, count = 1) {
  const ids = new Set(deaeratorPorts(power, count).openedCaps);
  const remove = [];
  da.traverse((o) => {
    const match = o.name.match(/(?:CAD.solid.|DA3_CAD_)(\d+)$/);
    if (match && ids.has(Number(match[1]))) remove.push(o);
  });
  remove.forEach((o) => o.removeFromParent());
  da.userData.connectedNozzles = deaeratorPorts(power, count);
  da.userData.supportElevation = nativeDeaerator(power, count)?.supportElevation || 0;
}

// <stdin>
var generated = (geometry, color) => {
  const m = new Mesh2(geometry, new MeshStandardMaterial2({ color, roughness: 0.6, metalness: 0.25 }));
  m.userData.generatedGeometry = true;
  return m;
};
var box = (p, s, c) => generated(new BoxGeometry3(s[0], s[2], s[1]).translate(...viewPoint(p)), c);
function cylinder2(id, a, b, r, color) {
  const d = new Vector32(...viewPoint(b)).sub(new Vector32(...viewPoint(a))), mid = new Vector32(...viewPoint(a)).add(new Vector32(...viewPoint(b))).multiplyScalar(0.5), geometry = new CylinderGeometry2(r, r, d.length(), 8);
  geometry.applyQuaternion(new Quaternion2().setFromUnitVectors(new Vector32(0, 1, 0), d.normalize()));
  geometry.translate(...mid.toArray());
  const m = generated(geometry, color);
  m.name = id;
  m.userData.semanticId = id;
  return m;
}
function applyLiteParts(scene, c, inputs) {
  if (scene.getObjectByName("lite_functional_parts")) throw Error("applyLiteParts must run once per scene");
  const borrowed = /* @__PURE__ */ new Set();
  for (const input of [inputs.trap, inputs.strainer]) input?.traverse((o) => {
    if (o.isMesh) borrowed.add(o.geometry);
  });
  const root = new Group4();
  root.name = "lite_functional_parts";
  scene.add(root);
  if (c.cascade > 1) {
    if (!inputs.trap) throw Error("Lite cascade needs canonical condensate_trap");
    const last = (c.cascade - 1) * unitSpacing, [gx, gy] = greyOrigin(c.cascade), support = new Group4();
    support.name = "cascade_supports";
    for (const x of [-0.55, ...Array.from({ length: c.cascade - 1 }, (_, i) => (i + 0.5) * unitSpacing), last + 0.7]) support.add(box([x, 5.6, 2.19], [0.1, 0.1, 4.38], 6846336), box([x, 5.6, 0.015], [0.38, 0.38, 0.03], 6846336), box([x, 5.6, 4.403], [0.3, 0.28, 0.025], 6846336));
    for (const dx of [-0.15, 0.15]) support.add(box([gx + dx, gy + 0.12, 0.73], [0.038, 0.038, 1.46], 6846336), box([gx + dx, gy + 0.06, 0.014], [0.1, 0.43, 0.028], 6846336));
    for (const z of [1.23, 1.48]) support.add(box([gx, gy + 0.137, z], [0.4, 0.028, 0.035], 6846336));
    root.add(support);
    const pressure = new Group4();
    pressure.name = "cascade_pressure_sensor";
    pressure.add(box([last + 0.3, 5.6, 4.86], [0.08, 0.055, 0.12], 14015966), box([last + 0.3, 5.571, 4.86], [0.048, 4e-3, 0.033], 2436144));
    root.add(pressure);
    root.add(distributionHardware(c.cascade, inputs.trap));
  }
  if (c.addons.includes("deaerator")) {
    if (!inputs.strainer) throw Error("Lite DA needs canonical ADL IS16 strainer");
    root.add(deaeratorHardware(c.power, c.cascade, inputs.strainer));
    const da = scene.getObjectByName("deaerator");
    if (!da) throw Error("Lite DA mesh missing");
    openDeaeratorPorts(da, c.power, c.cascade);
    if (selectDeaerator(c.power, c.cascade) === "da3") {
      const kx = -3.727, ky = -0.062, cx = kx - 0.18 * 0.8660254, cy = ky - 0.18 * 0.5;
      for (const z of [0.760313, 1.960313]) da.add(cylinder2("da3_K_" + z, [kx, ky, z], [cx, cy, z], 0.0135, 6583936));
      da.add(cylinder2("da3_level_column", [cx, cy, 0.69], [cx, cy, 2.03], 0.027, 5859185), cylinder2("da3_level_glass", [cx - 0.026, cy, 0.78], [cx - 0.026, cy, 1.94], 9e-3, 12102260));
    }
  }
  root.traverse((o) => {
    if (o.name === "da_fittings" || o.name.startsWith("cascade_")) o.userData.semanticId = o.name;
    if (o.isMesh && !borrowed.has(o.geometry)) o.userData.generatedGeometry = true;
  });
  return root;
}
export {
  applyLiteParts
};
