import {createRequire} from 'node:module';
import {resolve} from 'node:path';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const require=createRequire(resolve(process.env.S3000_BROWSER_RUNTIME,'package.json'));
const {chromium}=require('playwright');
const [base,out]=process.argv.slice(2);await mkdir(out,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const errors=[],checks=[];
try {
 const page=await browser.newPage({viewport:{width:1540,height:1040}});
 const manifestResponse=await page.request.get(base+'DEPLOY_MANIFEST.json');assert(manifestResponse.ok());
 const manifestSha256=createHash('sha256').update(await manifestResponse.body()).digest('hex');
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'?power=4000&trim=standard&inspect3d=1',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>window.__s3000?.scene?.getObjectByName('control_cabinet'),null,{timeout:180000});
 const visible=async name=>page.evaluate(name=>{let o=window.__s3000.scene.getObjectByName(name);if(!o)return false;while(o){if(!o.visible)return false;o=o.parent}return true},name);
 assert(await visible('control_cabinet'));assert(!await visible('plus_cabinet'));
 await page.getByLabel('Комплектация',{exact:true}).selectOption('comfort_plus');
 await page.waitForFunction(()=>window.__s3000?.scene?.getObjectByName('plus_cabinet'),null,{timeout:180000});
 assert(!await visible('control_cabinet'));assert(await visible('plus_cabinet'));
 await page.getByRole('button',{name:'Шкаф',exact:true}).click();await page.waitForTimeout(700);
 await page.screenshot({path:resolve(out,'comfort-plus-closed.png')});
 await page.getByRole('button',{name:'Открыть шкаф',exact:true}).click();
 await page.waitForFunction(()=>Math.abs(window.__s3000.scene.getObjectByName('photo_hinge_comfort_plus').rotation.y-105*Math.PI/180)<.0001);
 await page.screenshot({path:resolve(out,'comfort-plus-open.png')});checks.push('Standard preserved; Comfort+ replaces complete cabinet; door opens 105 degrees');
 await page.getByLabel('Установка',{exact:true}).selectOption('cascade');
 await page.waitForFunction(()=>window.__s3000?.scene?.getObjectByName('boiler_unit_2'),null,{timeout:180000});
 const state=await page.evaluate(()=>{
  const scene=window.__s3000.scene,u=scene.userData.units;
  const visible=o=>{if(!o)return false;while(o){if(!o.visible)return false;o=o.parent}return true};
  const counts={};for(const id of ['boiler','plus_cabinet','deaerator','separator_fv8','separator_bdv60_5','suction_common','steam_delivery'])counts[id]=u.filter(g=>visible(g.getObjectByName(id))).length;
  const a=u[0].getObjectByName('boiler'),b=u[1].getObjectByName('boiler');let am,bm;a.traverse(o=>{if(o.isMesh&&!am)am=o});b.traverse(o=>{if(o.isMesh&&!bm)bm=o});
  return {counts,units:u.length,spacing:u[1].position.x,geometryShared:am.geometry===bm.geometry,draws:window.__s3000.gl.info.render.calls};
 });
 assert.equal(state.units,2);assert.equal(state.spacing,6.3);assert(state.geometryShared);
 assert.deepEqual(state.counts,{boiler:2,plus_cabinet:2,deaerator:1,separator_fv8:1,separator_bdv60_5:1,suction_common:0,steam_delivery:2});
 assert(await visible('cascade_header'));assert(await visible('cascade_cabinet'));assert(new URL(page.url()).searchParams.get('cascade')==='2');
 await page.getByRole('button',{name:'Общий вид',exact:true}).click();await page.waitForTimeout(900);await page.screenshot({path:resolve(out,'cascade-overview.png')});
 Object.assign(state,await page.evaluate(()=>({draws:window.__s3000.gl.info.render.calls,triangles:window.__s3000.gl.info.render.triangles})));
 await page.getByRole('tab',{name:'Оборудование',exact:true}).click();
 assert(await page.getByText('Общий каскадный шкаф автоматики',{exact:true}).count()>=1);
 await page.getByRole('tab',{name:'Сборка',exact:true}).click();
 await page.getByRole('button',{name:'Открыть каскадный шкаф',exact:true}).click();
 await page.waitForFunction(()=>Math.abs(window.__s3000.scene.getObjectByName('photo_hinge_cascade').rotation.y-105*Math.PI/180)<.0001);
 await page.screenshot({path:resolve(out,'cascade-cabinet-open.png')});
 await page.getByRole('button',{name:'Открыть шкафы котлов',exact:true}).click();
 await page.waitForFunction(()=>window.__s3000.scene.userData.units.every(g=>Math.abs(g.getObjectByName('photo_hinge_comfort_plus').rotation.y-105*Math.PI/180)<.0001));
 await page.getByRole('button',{name:'Открыть дверь котла',exact:true}).click();
 await page.waitForFunction(()=>window.__s3000.scene.userData.units.every(g=>Math.abs(g.getObjectByName('opening_boiler').rotation.y+105*Math.PI/180)<.0001));
 checks.push('Two independent cabinet assemblies and boiler doors; single shared cascade cabinet, DA, FV and BDV; geometry reused');
 for(const name of [/^Экономайзер/,/^Деаэратор/,/^BDV/,/^FV/]) {
  const input=page.getByRole('checkbox',{name});await input.uncheck();await page.waitForTimeout(100);await input.check();
 }
 assert(await visible('cascade_header'));checks.push('Economizer, DA, FV and BDV toggles retain common header');
 await page.getByRole('button',{name:'Общий вид',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);await page.screenshot({path:resolve(out,'cascade-mobile.png')});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.setViewportSize({width:1540,height:1040});
 await page.getByLabel('Установка',{exact:true}).selectOption('single');
 await page.waitForFunction(()=>window.__s3000?.scene&&!window.__s3000.scene.getObjectByName('boiler_unit_2'));
 await page.getByLabel('Комплектация',{exact:true}).selectOption('standard');
 await page.waitForFunction(()=>window.__s3000?.scene.getObjectByName('control_cabinet')?.visible===true);
 assert(!await visible('cascade_header'));assert(!await visible('plus_cabinet'));
 checks.push('Mobile viewport fits; returning to single Standard removes cascade and restores original cabinet');
 assert.deepEqual(errors,[]);
 await writeFile(resolve(out,'report.json'),JSON.stringify({status:'PASSED_CASCADE_BROWSER',base,manifestSha256,checks,state,errors},null,2));
 console.log(JSON.stringify({checks,state,errors}));
} finally {await browser.close()}
