"""Small, source-bound connection table for the parametric web cascade.

Coordinates are metres, Z up, as in the accepted family CAD registrations.
No scaling of factory boilers or of their connection positions.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(r'E:\CodexArtifacts\Boiler-Family-v2026.09.13.6')
rows = {}
for power in [500,1000,1500,2000,2500,3000,3500,4000,5000]:
    d = json.loads((SOURCE/str(power)/'layout.json').read_text(encoding='utf8'))
    shift = d['moves']['steam_delivery']
    routes = {r['id']: r for r in d['routes']}
    r = d['registration']
    wiring = json.loads((SOURCE/str(power)/'wiring.json').read_text(encoding='utf8'))
    cable = next(w for w in wiring['routes'] if w['id']=='mod_eco_drive_cable')
    row = dict(steam_end=[shift[0],2.1+shift[1],3+shift[2]],
               bottom_nozzle=r['ports']['drain']['position_m'],
               bottom_split=routes['bottom_piping']['points'][-1],
               # Rear casing face: measured on all nine registered CAD meshes
               # at the photo drain height (ray hit tolerance < 0.02 mm).
               rear_face_y=r['ports']['flue']['position_m'][1]-.0375,
               cabinet_shift=d['moves']['control_cabinet'],
               feed_end=routes['direct_inlet']['points'][-1],
               direct_modulation=d['modulation']['center'],
               tds_end=routes['tds_common']['points'][-1],
               bottom_end=routes['bottom_discharge']['points'][-1],
               boiler_source_sha256=r['boiler_sha256'],
               modulation_gland=cable['points'][0],
               cabinet_gland=cable['points'][-1],
               # Existing presentation steam pipe has OD114 on every rating.
               # Preserve its joint; a new diameter is not inferred from capacity.
               steam_visual_radius=.057)
    if power >= 1500:
        eco=r['economizer']
        row['eco_in']=eco['ports']['water_in']['position_m']
        row['eco_out']=eco['ports']['water_out']['position_m']
        row['eco_source_sha256']=eco['sha256']
    rows[str(power)] = row
out=ROOT/'src/components/BoilerConfigurator/cascadeConnections.ts'
out.write_text('// Generated by tools/cascade/export_connections.py. Codex / GPT-6, 2026-10-01.\n'
               '// Source coordinates remain in metres, Z up.\n'
               'export const cascadeConnections = '+json.dumps(rows,ensure_ascii=False,indent=2)+' as const\n',encoding='utf8')
print('CONNECTIONS_EXPORTED',len(rows))
